### PR TITLE
Fix log message parsing for apps that use NativeLogging

### PR DESCRIPTION
**Pull request by bladealslayer**
Log messages do not contain the `APP_NAME:RELEASE/CONTAINER_ID` prefix when the app uses native logging.

### CODE REVIEW

**Comment by mattmanning** [comment]
[syslog resources sends misformed messages to syslog server](https://trello.com/c/xWaO4Ehw/2366-syslog-resources-sends-misformed-messages-to-syslog-server)

**Comment by nzoschke** [comment]
Thanks for the PR. I'll review this today.

**Comment by nzoschke** [comment]
Taking a look at this now. Made a little playground sketch to test: https://play.golang.org/p/tTojUvHt5n

**Comment by nzoschke** [comment]
Based on the output, it looks like there is no change to the non-native logging syslog message which is good. But I don't see any change to the native logging message either.

Maybe i'm missing something in the sketch?

```
<22>1 2016-04-15T01:00:44Z convox-httpd-LogGroup-1KIJO8SS9F3Q9 web:RGBCKLEZHCX ec329dcefd61 - - 10.0.3.37 - - [15/Apr/2016:01:00:44 +0000] "GET / HTTP/1.1" 304 -

<22>1 2016-04-15T01:00:44Z convox-httpd-LogGroup-1KIJO8SS9F3Q9 web:RGBCKLEZHCX ec329dcefd61 - - 10.0.3.37 - - [15/Apr/2016:01:00:44 +0000] "GET / HTTP/1.1" 304 -

Re.FindStringSubmatch miss
<22>1 2016-04-15T01:00:44Z convox-httpd-LogGroup-1KIJO8SS9F3Q9 convox/syslog unknown - - 10.0.3.37 - - [15/Apr/2016:01:00:44 +0000] "GET / HTTP/1.1" 304 -

<22>1 2016-04-15T01:00:44Z convox-httpd-LogGroup-1KIJO8SS9F3Q9 convox/syslog unknown - - 10.0.3.37 - - [15/Apr/2016:01:00:44 +0000] "GET / HTTP/1.1" 304 -
```

**Comment by bladealslayer** [comment]
Try with a message that would otherwise match the original regex. The issue was that the original regex was too relaxed and for example, JSON log messages could easily match. Consider a log message:

`{"path": "GET /v1/api/_health", "status": 200}`

So, the fix isn't really bulletproof, but makes the regex a bit tighter and less likely to match (it will work for all cases where the first space-separated field in the log does not match the `([^: ]+):([^/ ]+)/([^ ]+) )` portion. It can be made even tighter, if we can restrict the character set for the app name, release and container ID portions, which I realise now would probably have been better.

Here's sketch: https://play.golang.org/p/WuwMl-etdd

**Comment by nzoschke** [comment]
@bladealslayer ok thanks for the extra information. Do you want to take a crack at an even tighter regex while we're looking at this? Or is it good as proposed?

**Comment by bladealslayer** [comment]
Sure, I can do that. Could you tell what characters are allowed in app
names? I suppose that release and container id both only allow just letters
and numbers?

**Comment by nzoschke** [comment]
App names have to start with a letter and can contain letters, numbers and a minus sign like `api-staging-2`.

Release IDs are all upper case letters like `RUNHJJZLRIA`.

Container IDs are UUIDs like `c5cba4eb-5dad-405e-96db-71ef8eefe6a8`

The underlying logic comes from the fact that apps are cloud formation stacks, which have this validation:

> fn-create-stack: Malformed input-1 validation error detected: Value 'stack_underscore' at
'stackName' failed to satisfy constraint: Member must satisfy regular
expression pattern: a-zA-Z-a-zA-Z0-9*

Convox adds a bit more constraint:

> $ convox apps create _FOOOO
> app name can contain only alphanumeric characters, dashes and must be between 4 and 30 characters

**Comment by bladealslayer** [comment]
@nzoschke I made the regex tighter. Updated playground: https://play.golang.org/p/diqgUU2vQZ

**Comment by mattmanning** [comment]
This looks good in my testing.

**Pull request merged**
